behaviors:
  TestAgent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    checkpoint_interval: 500000

    max_steps: 500000

    time_horizon: 64

    summary_freq: 10000

    threaded: false
